version: "3"

services:
  sqs:
      image: softwaremill/elasticmq:latest
      ports:
        - "9324:9324"
  dynamodb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - adora-dynamodb:/home/dynamodblocal/db

volumes:
  adora-dynamodb:
    driver: local