service: adora

plugins:
 - serverless-plugin-typescript
 - serverless-plugin-optimize
 - serverless-offline
 - serverless-offline-watcher

custom:
  serverless-offline-watcher:
    - path: src/lambda.ts
      command: echo "lambda.ts was modified!"
    - path:
        - src
      command: echo "api folder or js file in cow folder was modified!"


provider:
 name: aws
 runtime: nodejs16.x

functions:
 main: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/lambda'
   handler: src/lambda.handler
   events:
     - http:
         method: any
         path: /{any+}